name: Release

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
  workflow_dispatch:
    inputs:
      tag:
        description: "Git tag to release from"
        required: true
        type: string

jobs:
  publish-lib:
    env:
      SPHA_LIB_VERSION: ${{ inputs.tag || github.ref_name }}
    permissions:
      contents: write
    runs-on: ubuntu-24.04
    environment: Deploy
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8
        with:
          ref: ${{ env.SPHA_LIB_VERSION }}
      - name: Set up Apache Maven Central
        uses: actions/setup-java@f2beeb24e141e01a676f977032f5a29d81c9e27e
        with: # running setup-java again overwrites the settings.xml
          distribution: 'temurin'
          java-version: '24'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@4d9f0ba0025fe599b4ebab900eb7f3a1d93ef4c2

      - name: Package distribution
        run: ./gradlew distZip

      # - name: Publish to Maven Central
      #   env:
      #     SPHA_LIB_VERSION: ${{ env.SPHA_LIB_VERSION }}
      #     ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.SONATYPE_USER }}
      #     ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.SONATYPE_PW }}
      #     ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.GPG_PRIVATE_KEY }}
      #     ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.GPG_PRIVATE_KEY_PASSPHRASE }}
      #   run: ./gradlew :lib:core:publishToMavenCentral :lib:adapter:publishToMavenCentral :lib:model:publishToMavenCentral --no-configuration-cache

      # TODO: Changelog shouldn't contain UI / cli changes
      - name: Generate Release Notes
        run: |
          prev_tag=$(git tag --sort=-v:refname | awk -v t="$SPHA_LIB_VERSION" '$0 ==t {seen = 1; next }; seen { print; exit }')
          git log --pretty=oneline $prev_tag..HEAD -- lib > RELEASE_NOTES.Example.md
          # Make clean RELEASE_NOTES
          ./gradlew -q printChangeLog > RELEASE_NOTES.md

      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # TODO: suggestion to release lib-VERSION and cli-VERSION later on
        run: |
          gh release create $SPHA_LIB_VERSION --notes-file RELEASE_NOTES.md RELEASE_NOTES.Example.md build/distributions/*.zip 
